name: Java CI with Maven & CodeQL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 12 * * 1'  # CodeQL tourne chaque lundi à 12h UTC

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  codeql-analysis:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'pull_request')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          setup-java-options: |
            --include-dependencies

      - name: Build Java project (for CodeQL)
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true

      - name: Debug - List compiled files
        run: |
          echo "Listing compiled files in target/classes..."
          ls -R target/classes || echo "No compiled files found."

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          verbosity: debug
