name: Java CI with Maven & CodeQL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 12 * * 1'  # CodeQL tourne chaque lundi à 12h UTC

permissions:
  actions: read
  contents: read
  security-events: write  # ⬅️ Important pour CodeQL

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven  # Utilise le cache Maven intégré

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        env:
          POSTGRESQL_ADDON_DB: ${{ secrets.POSTGRESQL_ADDON_DB }}
          POSTGRESQL_ADDON_HOST: ${{ secrets.POSTGRESQL_ADDON_HOST }}
          POSTGRESQL_ADDON_PORT: ${{ secrets.POSTGRESQL_ADDON_PORT }}
          POSTGRESQL_ADDON_USER: ${{ secrets.POSTGRESQL_ADDON_USER }}
          POSTGRESQL_ADDON_PASSWORD: ${{ secrets.POSTGRESQL_ADDON_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn -B package --file pom.xml

      - name: Run Tests
        env:
          POSTGRESQL_ADDON_DB: ${{ secrets.POSTGRESQL_ADDON_DB }}
          POSTGRESQL_ADDON_HOST: ${{ secrets.POSTGRESQL_ADDON_HOST }}
          POSTGRESQL_ADDON_PORT: ${{ secrets.POSTGRESQL_ADDON_PORT }}
          POSTGRESQL_ADDON_USER: ${{ secrets.POSTGRESQL_ADDON_USER }}
          POSTGRESQL_ADDON_PASSWORD: ${{ secrets.POSTGRESQL_ADDON_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn test

      - name: Debug Build Failure
        if: failure()
        run: |
          echo "Build failed. Printing logs..."
          cat target/surefire-reports/*.txt || true
          echo "Printing Maven build log..."
          cat target/build.log || true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  codeql-analysis:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'pull_request')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug - List project files
      run: |
        echo "Listing project files..."
        ls -R || echo "Failed to list files."

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Build Java project
      run: mvn clean install -DskipTests -X

    - name: Debug - List compiled files
      run: |
        echo "Listing compiled files in target/classes..."
        ls -R target/classes || echo "No compiled files found."

    - name: Clean CodeQL database
      run: |
        echo "Cleaning CodeQL database..."
        rm -rf /home/runner/work/_temp/codeql_databases

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        debug: true
